# Generated by Django 3.1.5 on 2021-01-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Under_Caregories',
            new_name='Under_Categories',
        ),
        migrations.RenameField(
            model_name='sites',
            old_name='under_caregory',
            new_name='under_category',
        ),
    ]
